group 'dev.kelvinforteta.flutter_help_scout'
version '1.0'
apply from: './dependencies.gradle'

rootProject.allprojects {
    repositories {
        google()
        maven { url 'https://maven.google.com' }
        mavenCentral()

    }
}

apply plugin: 'com.android.library'

android {
    namespace 'dev.kelvinforteta.flutter_help_scout'
    compileSdk 34

    defaultConfig {
        minSdkVersion 21
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation "com.helpscout:beacon:$beaconVersion"
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.13.0'
    implementation 'com.android.support:multidex:2.0.1'
}
