group 'dev.kelvinforteta.flutter_help_scout'
version '1.0'

buildscript {
    apply from: './dependencies.gradle'
    repositories {
        google()
        maven {
            url 'https://maven.fabric.io/public'
        }
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        maven { url 'https://maven.google.com' }
        mavenCentral()

    }
}

apply plugin: 'com.android.library'

android {
    compileSdk 34

    defaultConfig {
        minSdkVersion 21
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation "com.helpscout:beacon:$beaconVersion"
//    implementation 'com.android.support:multidex:2.0.1'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'androidx.core:core-ktx:1.2.0'
}
